### ISSUE TITLE
getTableRow is not called anywhere, what invokes it.how its called

### ISSUE THREAD

**Issue by yashwanth2804** [EOSIO/eosio-project-demux-example#34]
`getTableRows = (scope, table) => this.eosio.getTableRows(true, this.contractAccount, scope, table);
`
this code in eosio-client.js in utils folder

**Comment by TaraTritt** [comment]
Yes, you are correct this function is not being used anywhere in the code because instead of querying the multi index table for our contract, we are utilizing demux to store the state of our application. Demux stores the state in our mongodb database which is what we are querying in our application to read the blog posts. This function was left in as reference of how the multi index table could be queried if needed, but I could see how this could be confusing since it is not being used anywhere. I'll open a PR to remove this to avoid confusion, thanks!

**Comment by TaraTritt** [comment]
#35
