### ISSUE TITLE
[Question]  How Demux recreated data to my mongodb,even after I deleted DB. where smartcontract stores only few fields

### ISSUE THREAD

**Issue by yashwanth2804** [EOSIO/eosio-project-demux-example#36]
I have little confusion,
when i sent eosio transaction,payload data is being stored in mongodb by demux.
So my question is, is blockchain smart contract storing all payload data or only few as parameters
namely post.key,post.skey,post.author 

```
 eosio_docker/contracts/blog/blog.cpp/ //@abi action createpost

 poststable.emplace(author, [&](auto &post) {
      post.pkey = poststable.available_primary_key();
      post.skey = skey;
      post.author = author;
    });
```
Storing post content data is bad idea,and i need only few to be in blockchain and most fields in db

**Comment by TaraTritt** [comment]
Yes, we are only storing a few things in the multi index table on the blockchain to reduce RAM usage. The limited data we are storing is only used to validate that the author is the only user that can edit & delete their own posts

```
// check if authorized to update post
require_auth(post->author);
...
// check if authorized to delete post
require_auth(post->author)
```

**Comment by yashwanth2804** [comment]
In my case i ran these steps
1 . Stopped db
2 . now frontend will post via eosio.transaction
( To my knowledge  eosio.tranaction writes to blockchain first then demux gets the block and writes to db)
3 as DB is off, no newly created post will be on db
4 When I restart the DB , I got post that were made while db in off state.

( so demux check last block it processed and downloads from where it left from blockchain,
in that case post title,author,tag as payload got to db 
if blockchain store only pkey,skey,author . how i got payload data to db
)

**Comment by TaraTritt** [comment]
Even though most of the blog post data is not being stored in the multi index table they are still included in the payload of the transaction. Since demux stores the last block it has processed as soon as the process is running again, it will start processing blocks until it catches up to the latest blocks in the chain. Processing these blocks includes inspecting the payloads of the transactions. See the createpost updater
```
async function createPost (state, payload, blockInfo, context) {
```

If you were to `console.log(payload)` you would see all the blog post data sent with the transaction (title, content, tag, author ...)
