### ISSUE TITLE
Why is the updater implemented asynchronously and the effect implemented synchronously?

### ISSUE THREAD

**Issue by ttamna** [EOSIO/eosio-project-demux-example#49]
You did not say that, did you?

https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/handlerVersions/v1/index.js#L56

**Comment by TaraTritt** [comment]
Updaters are always awaited, meaning any asynchronous functionality in your updater code will finish executing before demux continues processing the next block. However, effects are not awaited, so they can still be asynchronous, but demux will not wait for the function to finish executing. In the [demux handleActions](https://github.com/EOSIO/demux-js/blob/develop/src/AbstractActionHandler.ts) code:
```
    const versionedActions = await this.applyUpdaters(state, block, isReplay, context)
    if (!isReplay) {
      this.runEffects(versionedActions, block, context)
    }
```

**Comment by flux627** [comment]
I think the confusion arises due to the confusing way Javascript has named things- in order to run asynchronous code synchronously in Javascript, you need to label functions as `async` and then `await` them. (Labelling `async` is just syntactic sugar that wraps the function in a Promise.) Therefore, since we want all updater functions to run synchronously, we must label the functions `async`.

**Comment by ttamna** [comment]
@flux627 @TaraTritt  Aha! that's right. i was hesitated. Thank you
